# -*- coding: utf-8 -*-
# Deployment settings for memorygame.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['D:/Marmalade/6.1/s3e/makefile_builder/mkb.py', 'c:/Users/dreambit/Documents/memorygame/memorygame.mkb', '--default-buildenv=vc10', '--msvc-project', '--deploy-only']
mkb = 'c:/Users/dreambit/Documents/memorygame/memorygame.mkb'
mkf = ['d:\\marmalade\\6.1\\modules\\iw2d\\iw2d.mkf', 'd:\\marmalade\\6.1\\modules\\iwgx\\iwgx.mkf', 'd:\\marmalade\\6.1\\modules\\iwgeom\\iwgeom.mkf', 'd:\\marmalade\\6.1\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\dreambit\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\dreambit\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\dreambit\\appdata\\roaming\\marmalade\\packages\\6.1.1\\zlib_1.2.4\\zlib.mkf', 'd:\\marmalade\\6.1\\modules\\iwresmanager\\iwresmanager.mkf', 'd:\\marmalade\\6.1\\modules\\iwgl\\iwgl.mkf', 'd:\\marmalade\\6.1\\modules\\iwgxfont\\iwgxfont.mkf', u'c:\\users\\dreambit\\appdata\\roaming\\marmalade\\packages\\6.1.1\\tiniconv_1.0.1\\tiniconv.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/dreambit/Documents/memorygame\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'memorygame'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'memorygame'
    long_caption = 'memorygame'
    version = [0, 0, 1]
    config = ['c:/Users/dreambit/Documents/memorygame/data/app.icf']
    data_dir = 'c:/Users/dreambit/Documents/memorygame/data'
    iphone_link_lib = []
    playbook_author = 'dreambitc'
    linux_ext_lib = []
    iphone_link_libdir = []
    playbook_authorid = 'gYAAgA8XHY6RUvCxDXH1BI2BprM'
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'c:/Users/dreambit/Documents/memorygame/build_memorygame_vc10/Debug_memorygame_VC10_arm/memorygame.s3e',
                   'release' : r'c:/Users/dreambit/Documents/memorygame/build_memorygame_vc10/Release_memorygame_VC10_arm/memorygame.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/dreambit/Documents/memorygame/build_memorygame_vc10/Debug_memorygame_VC10_gcc_mips/memorygame.so',
                   'release' : r'c:/Users/dreambit/Documents/memorygame/build_memorygame_vc10/Release_memorygame_VC10_gcc_mips/memorygame.so',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/dreambit/Documents/memorygame/build_memorygame_vc10/Debug_memorygame_VC10_x86/memorygame.s86',
                   'release' : r'c:/Users/dreambit/Documents/memorygame/build_memorygame_vc10/Release_memorygame_VC10_x86/memorygame.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/dreambit/Documents/memorygame/build_memorygame_vc10/Debug_memorygame_VC10_gcc_arm/memorygame.s3e',
                   'release' : r'c:/Users/dreambit/Documents/memorygame/build_memorygame_vc10/Release_memorygame_VC10_gcc_arm/memorygame.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
